adjective = input("Pick an adjective: ")
adjective2 = input("Pick another adjective: ")
type_of_bird = input("Pick a type of bird: ")
room_in_the_house = input("Pick a room in a house: ")
verb_past_tense = input("Pick a verb past tense: ")
verb = input("Pick a verb: ")
relative_name = input("Pick a relative's name: ")
noun = input("Pick a noun: ")
liquid =  input("Pick a liquid: ")
verb_ing = input("Pick a verb that ends with -ing: ")
part_of_body_plural = input("Pick a part of body (plural): ")
plural_noun = input("Pick a plural noun: ")
verb_ing2 = input("Pick another verb that ends with -ing: ")
noun2 = input("Pick another noun: ")
print("")
print("Here is your story:")
print("")
print("It was a", adjective, ", cold November day. I woke up to the", adjective2, "smell of", type_of_bird, "rosating in the", room_in_the_house, "downstairs. I", verb_past_tense, "down the stairs to see if I could help", verb, "My mom said, \"See if", relative_name, "needs a fresh", noun, ".\"", "So I carried a tray of glasses full of", liquid, "into the", verb_ing, "room. When I got there, I couldn't believe my", part_of_body_plural, "! There were", plural_noun, verb_ing2, "on the", noun2)
print("")
print("Mad Libs Python Game by Tushar Passi")
print("Mad Libs Python ਗੇਮ ਤੁਸ਼ਾਰ ਪਾਸੀ ਨੇ ਬਣਾਇਆ")
print("")
print("Source of Mad Libs: \n\
https://usercontent1.hubstatic.com/7301022.png (hobbylark.com)")
